### ISSUE TITLE
Language/Citizenship Application

### ISSUE THREAD

**Issue by judyfong** [jokull/awesome-reykjavik#18]
There is currently a language page: https://www.awesome-rvk.is/guides/language/

But I would like it to have a couple of more things. 1. I would like it to mention that the third and like fourth biggest languages in Iceland tend to be Polish and like Ukranian/Lithuanian due to the large immigrant populations here, which can be seen in Statistics Iceland.

Another great place to learn Icelandic is through haskoli islands BA and pratical diploma programs: https://english.hi.is/school_of_humanities_faculty_of_icelandic_and_comparative_cultural_studies/icelandic_as_a_second

Also mms.is has a lot of free icelandic learning resources: http://tungumalatorg.is/ifa/

Finally, most importantly in order to become icelandic citizens, people need to pass and icelandic language test generally and here is the example from the govt: https://mms.is/sites/mms.is/files/synisprof_ipr_24.pdf
This test as well as the residency test is administered by mimir on behalf of the government.

 It would be great if this stuff could be added. Thanks!

**Comment by jokull** [comment]
Thank you for sharing! Great resources. Are you interested in contributing a pull request for this?

**Comment by judyfong** [comment]
Not currently. I am busy right now. So if someone wants to make the PR,
feel free. However, if no one else manages to get to it before me (I think
i’ll have more time in August, but no promises), then i’ll try to make one.

**Comment by judyfong** [comment]
I finally found the time but i forgot a couple links https://studentabladid.is/efni/2023/12/14/umskn-um-rkisborgarartt-prf-verleikum

https://studentabladid.is/efni/2023/12/14/vi-erum-innlendingar-upplifun-nemanda-slensku-sem-annars-mls
